SOURCES = {
    "coindesk": {
        "id": "coindesk",
        "label": "CoinDesk",
        "feed": "https://www.coindesk.com/arc/outboundfeeds/rss/?output=xml",
        "focus": ["market", "industry"],
        "weight": 1,
    },
    "theblock": {
        "id": "theblock",
        "label": "The Block",
        "feed": "https://www.theblock.co/rss.xml",
        "focus": ["market", "research"],
        "weight": 1,
    },
    "blockworks": {
        "id": "blockworks",
        "label": "Blockworks",
        "feed": "https://blockworks.co/feed",
        "focus": ["macro", "institutional"],
        "weight": 1,
    },
    "cointelegraph": {
        "id": "cointelegraph",
        "label": "Cointelegraph",
        "feed": "https://cointelegraph.com/rss",
        "focus": ["market", "global"],
        "weight": 1,
    },
    "thedefiant": {
        "id": "thedefiant",
        "label": "The Defiant",
        "feed": "https://thedefiant.io/feed",
        "focus": ["defi"],
        "weight": 1,
    },
    "dlnews": {
        "id": "dlnews",
        "label": "DL News",
        "feed": "https://www.dlnews.com/feed",
        "focus": ["defi", "regulation"],
        "weight": 1,
    },
    "protos": {
        "id": "protos",
        "label": "Protos",
        "feed": "https://protos.com/feed",
        "focus": ["investigation"],
        "weight": 1,
    },
    "decrypt": {
        "id": "decrypt",
        "label": "Decrypt",
        "feed": "https://decrypt.co/feed",
        "focus": ["culture", "technology"],
        "weight": 1,
    },
    "cryptopanic": {
        "id": "cryptopanic",
        "label": "CryptoPanic",
        "feed": "https://cryptopanic.com/rss/",
        "focus": ["aggregator"],
        "weight": 2,
    },
    "messari": {
        "id": "messari",
        "label": "Messari",
        "feed": "https://messari.io/rss",
        "focus": ["research", "data"],
        "weight": 1,
    },
    "glassnode": {
        "id": "glassnode",
        "label": "Glassnode Insights",
        "feed": "https://insights.glassnode.com/rss",
        "focus": ["on-chain", "analytics"],
        "weight": 1,
    },
}
